<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <InvariantGlobalization>true</InvariantGlobalization>
    <IsPackable>false</IsPackable>
    <EnableMauiImageProcessing>false</EnableMauiImageProcessing>
    <EnableMauiSplashScreenProcessing>false</EnableMauiSplashScreenProcessing>
    <EnableMauiFontProcessing>false</EnableMauiFontProcessing>
    <EnableMauiAssetProcessing>false</EnableMauiAssetProcessing>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HealthGoalsTracker.csproj"
                      AdditionalProperties="TargetFramework=net10.0-windows10.0.19041.0" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>